### ISSUE TITLE
About exercices...

### ISSUE THREAD

**Issue by dahfazz** [Sfeir/css-200#15]
Est-ce qu'on maintient l'idée de faire tous les exos sur l'appli PEOPLE ou est-ce qu'on propose une page dédiée à chaque exercice pour être libre de proposer un cas bien adapté à chaque fois ?

ping @roxyska @raphaelbauduin

**Comment by roxyska** [comment]
si on garde l'appli PEOPLE il ne faut pas se limiter à ce qu'elle est actuellement, ne pas hésiter à ajouter des éléments dedans etc.
L'avantage des cas bien adaptés à chaque fois c'est qu'on peut plus facilement faire des choses sans avoir du code perturbant autour

du coup je pencherais bien pour des cas bien adaptés à chaque situation, ce qui n'empêche pas de rester dans l'univers sfeir (au contraire).
